In [1]:
# 리스트, 튜플, if 문, for 문, 함수의 예문을 하나씩 해보자

import numpy as np

a = np.array(
    [
        [0, 1, 2],
        [3, 4, 5]
    ]
)

b = np.array(
    [
        [5, 4, 3],
        [2, 1, 0]
    ]
)

print(a + b)
print()
print(a - b)
print()
print(a * b)

[[5 5 5]
 [5 5 5]]

[[-5 -3 -1]
 [ 1  3  5]]

[[0 4 6]
 [6 4 0]]
