In [ ]:
# NumPy의 배열은 array() 함수를 사용함으로써 생성한다

In [1]:
# Python의 리스트로부터 NumPy 배열을 만든다
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5])

print(a)

[0 1 2 3 4 5]


In [3]:
# 2중 리스트로부터 NumPy의 2차원 배열을 만든다
import numpy as np

b = np.array(
    [
        [0, 1, 2], 
        [3, 4, 5]
    ]
)
print(b)

[[0 1 2]
 [3 4 5]]


In [4]:
# 3중 리스트로부터 NumPy의 3차원 배열을 만든다
import numpy as np


c = np.array(
    [
        [[0, 1, 2], [3, 4, 5]], 
        [[5,4,3], [2, 1, 0]]
    ]
)

In [5]:
# 배열을 생성하는 다양한 함수
# zeros(): 요소가 모두 0인 배열 생성
# ones(): 요소가 모두 1인 배열 생성
# arange(): 0부터 인수 이전까지 정수가 차례대로 나열된 배열 생성

import numpy as np

d = np.zeros(8)
print(d)

e = np.ones(8)
print(e)

f = np.arange(8)
print(f)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7]
