In [1]:
# 배열과 수치의 연산

import numpy as np

a = np.array(
    [
        [0, 1, 2],
        [3, 4, 5]
    ]
)

print(a)
print()
print(a + 3)
print()
print(a * 3)

[[0 1 2]
 [3 4 5]]

[[3 4 5]
 [6 7 8]]

[[ 0  3  6]
 [ 9 12 15]]


In [2]:
# 배열끼리의 연산

b = np.array(
    [
        [0, 1, 2],
        [3, 4, 5]
    ]
)

c = np.array(
    [
        [2, 0, 1],
        [5, 4, 33]
    ]
)

print(b)
print()
print(c)
print()
print(b + c)
print()
print(b - c)

[[0 1 2]
 [3 4 5]]

[[ 2  0  1]
 [ 5  4 33]]

[[ 2  1  3]
 [ 8  8 38]]

[[ -2   1   1]
 [ -2   0 -28]]
