In [1]:
# 인덱스를 지정하고, 배열의 요소로 접근한다

import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[3])

4


In [2]:
# 인덱스를 지정해서 배열의 요소를 바꾼다
a[2] = 9
print(a)

[1 2 9 4 5]


In [3]:
# 2차원 배열의 요소로 접근한다
b = np.array(
    [
        [0, 1, 2],
        [3, 4, 5]
    ]
)

print(b[1, 2])

5


In [4]:
# 2차원 배열의 요소를 바꾼다
b[1, 2] = 9

print(b)

[[0 1 2]
 [3 4 9]]


In [5]:
# 행이나 열에 접근한다
c = np.array(
    [
        [0, 1, 2],
        [3, 4, 5]
    ]
)

print(c[1, :])
print()
c[:, 1] = np.array([6, 7])
print(c)

[3 4 5]

[[0 6 2]
 [3 7 5]]
